module.exports = {
  content: ["./client/index.html", "./client/src/**/*.{js,jsx,ts,tsx}",
    "./src/**/*.{html,js,ts,jsx,tsx}",
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "additional-colorswhite": "var(--additional-colorswhite)",
        black: "var(--black)",
        "dark-bag": "var(--dark-bag)",
        "foundationgreygrey-500": "var(--foundationgreygrey-500)",
        gold: "var(--gold)",
        "lightgray-0": "var(--lightgray-0)",
        "lightgray-11": "var(--lightgray-11)",
        "lite-black-grey": "var(--lite-black-grey)",
        "medium-gray2": "var(--medium-gray2)",
        "neutral-6": "var(--neutral-6)",
        "primaryblack-2": "var(--primaryblack-2)",
        "primaryf-1": "var(--primaryf-1)",
        primarywhite: "var(--primarywhite)",
        primaryyellow: "var(--primaryyellow)",
        "s-1": "var(--s-1)",
        "shades-of-black-black": "var(--shades-of-black-black)",
        "shades-of-black-grey8": "var(--shades-of-black-grey8)",
        "shades-of-blackblack": "var(--shades-of-blackblack)",
        "shades-of-blackgrey3": "var(--shades-of-blackgrey3)",
        "shades-of-blackgrey4": "var(--shades-of-blackgrey4)",
        "shades-of-blackgrey5": "var(--shades-of-blackgrey5)",
        "shades-of-blackgrey7": "var(--shades-of-blackgrey7)",
        "tertiaryt-2": "var(--tertiaryt-2)",
        "tertiaryt-3": "var(--tertiaryt-3)",
        white: "var(--white)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        "APP-input-16m": "var(--APP-input-16m-font-family)",
        "APP-title-5-20m": "var(--APP-title-5-20m-font-family)",
        sans: [
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [require("tailwindcss-animate"), require("@tailwindcss/typography")],
  darkMode: ["class"],
};
